
package InterfazGrafica;

import Clases.Aula;
import Dtos.AulaDTO;
import Dtos.ListaReservaDTO;
import Gestores.GestorAula;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


public class BuscarAula extends javax.swing.JFrame {
    
    private GestorAula gAula;
    private MenuBedel mBedel;
    
    public BuscarAula() {
        initComponents();
        
        gAula = new GestorAula();
        
        ArrayList<String> numAulas = new ArrayList<>();
        numAulas = gAula.buscarIds();
        
        for (String ids : numAulas) {
            numero.addItem(ids);
        }
        
        centrarColumnas();
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.setRowSelectionAllowed(true); 
        tabla.setColumnSelectionAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        numero = new javax.swing.JComboBox<>();
        tipo = new javax.swing.JComboBox<>();
        capacidad1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        modificar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(830, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(242, 240, 235));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(242, 240, 235));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TIPO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 60, -1, -1));

        jLabel2.setBackground(new java.awt.Color(242, 240, 235));
        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NÚMERO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setBackground(new java.awt.Color(242, 240, 235));
        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CAPACIDAD:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(242, 240, 235));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buscar.setBackground(new java.awt.Color(242, 240, 235));
        buscar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        buscar.setForeground(new java.awt.Color(0, 0, 0));
        buscar.setText("BUSCAR");
        buscar.setAlignmentY(0.0F);
        buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel2.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 110, 30));

        numero.setBackground(new java.awt.Color(242, 240, 235));
        numero.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        numero.setForeground(new java.awt.Color(153, 153, 153));
        numero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        numero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        jPanel2.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 65, 150, 30));

        tipo.setBackground(new java.awt.Color(242, 240, 235));
        tipo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        tipo.setForeground(new java.awt.Color(153, 153, 153));
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "MULTIMEDIOS", "INFORMATICA", "SIN RECURSOS" }));
        tipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        jPanel2.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 65, 150, 30));
        jPanel2.add(capacidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 65, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 940, 160));

        tabla.setBackground(new java.awt.Color(242, 240, 235));
        tabla.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        tabla.setForeground(new java.awt.Color(0, 0, 0));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NUMERO", "PISO", "TIPO", "CAPACIDAD", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla.setFocusable(false);
        tabla.setGridColor(new java.awt.Color(153, 153, 153));
        tabla.setRowHeight(30);
        tabla.setSelectionBackground(new java.awt.Color(242, 240, 235));
        tabla.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 770, 390));

        modificar.setBackground(new java.awt.Color(242, 240, 235));
        modificar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        modificar.setForeground(new java.awt.Color(0, 0, 0));
        modificar.setText("MODIFICAR");
        modificar.setAlignmentY(0.0F);
        modificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 130, 30));

        cancelar.setBackground(new java.awt.Color(242, 240, 235));
        cancelar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 0, 0));
        cancelar.setText("CANCELAR");
        cancelar.setAlignmentY(0.0F);
        cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int fila = tabla.getSelectedRow();
        
        if(fila!=-1){
            
            String[] datosAula = new String[3];
            datosAula=recuperarFila(fila);
         
            
            if(datosAula[2].equals("Multimedios")){
                ModificarMultimedios mMultimedios = new ModificarMultimedios(mBedel,datosAula[0]);
                mMultimedios.setVisible(true);
                mMultimedios.setLocationRelativeTo(null);
                mMultimedios.setResizable(false);
                this.setVisible(false);
                
            }else if(datosAula[2].equals("Informatica")){
                ModificarInformatica mInformatica = new ModificarInformatica(mBedel,datosAula[0]);
                mInformatica.setVisible(true);
                mInformatica.setLocationRelativeTo(null);
                mInformatica.setResizable(false);
                this.setVisible(false);
                
            }else{
                ModificarSinRecursos mSinRecursos = new ModificarSinRecursos(mBedel,datosAula[0]);
                mSinRecursos.setVisible(true);
                mSinRecursos.setLocationRelativeTo(null);
                mSinRecursos.setResizable(false);
                this.setVisible(false);
            }
            
            
        }else{
            mensajeNoSelecciona();
        }

    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        
        String num = (String)numero.getSelectedItem();
        String tipo1 = (String)tipo.getSelectedItem();
        int capacidad = (int)capacidad1.getValue();
        
        ArrayList<AulaDTO> aulas = new ArrayList<>();
        aulas = gAula.buscarAulas(num,tipo1,capacidad);
        
        if(aulas.isEmpty()){
            mensajeFracaso();
        }else{
            cargarDatos(aulas);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void centrarColumnas() {
        // Crear un renderizador para centrar el texto
        javax.swing.table.DefaultTableCellRenderer renderer = new javax.swing.table.DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // Aplicar el renderizador a cada columna de la tabla
        for (int i = 0; i < tabla.getColumnCount(); i++) {
            tabla.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }
    
    private void cargarDatos(ArrayList<AulaDTO> aulas) {
        // Obtén el modelo de la tabla
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabla.getModel();

        // Limpia las filas existentes en la tabla
        model.setRowCount(0);

        // Agrega cada BedelDTO como una fila en la tabla
        for (AulaDTO aula : aulas) {
            model.addRow(new Object[]{
                aula.getNumero(), 
                aula.getPiso(),
                aula.getTipo(), 
                aula.getCapacidad(),
                aula.getDisponible()
            });
        }
    }
    
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        mBedel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    public void setMenuBedel(MenuBedel mBedel){
        this.mBedel = mBedel;
    }
    
    public String[] recuperarFila(int fila){
        int columnas = tabla.getColumnCount();
        String[] datosFila = new String[3];
        // Iterar por todas las columnas de la fila seleccionada
        for (int i = 0; i < 3; i++) {
            if(i==2){
                datosFila[i] = (String) tabla.getValueAt(fila, i);
            }else{
                datosFila[i] = String.valueOf(tabla.getValueAt(fila, i));
            } 
        }
        return datosFila;
    }
    
    public void mensajeNoSelecciona(){
        UIManager.put("OptionPane.background", new Color(242,240,235));
        //UIManager.put("Panel.background", new Color(242,240,235));
        UIManager.put("OptionPane.messageFont", new Font("Bahnschirift",Font.BOLD,14));
        JOptionPane.showMessageDialog(null, "SELECCIONE UN AULA A MODIFICAR.","¡ALGO SALIO MAL!",
                JOptionPane.PLAIN_MESSAGE, getIcon("/cancelar.png",32,32));
    }
    
    public void mensajeFracaso(){
        UIManager.put("OptionPane.background", new Color(242,240,235));
        //UIManager.put("Panel.background", new Color(242,240,235));
        UIManager.put("OptionPane.messageFont", new Font("Bahnschirift",Font.BOLD,14));
        JOptionPane.showMessageDialog(null, "NO EXISTEN AULAS CON ESOS CRITERIOS.","¡ALGO SALIO MAL!",
                JOptionPane.PLAIN_MESSAGE, getIcon("/cancelar.png",32,32));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JSpinner capacidad1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JComboBox<String> numero;
    private javax.swing.JTable tabla;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables

    private Icon getIcon(String ruta, int w, int h) {
        return new ImageIcon(new ImageIcon(getClass().getResource(ruta))
                .getImage().getScaledInstance(w, h, 0));
    }
}
